name = "ChowLiuTrees"
uuid = "be466665-d60c-4e0a-9ae9-070eb5e678a5"
authors = ["Guy Van den Broeck <guyvdb@cs.ucla.edu>"]
version = "0.1.2"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
CUDA = "3"
DataStructures = "0.17, 0.18"
julia = "1.6"
